import * as d3 from "d3";

export const nodeColor = d3
  .scaleOrdinal()
  .domain([
    "Aggregate",
    "Group",
    "Sort",
    "Order",
    "Seq Scan",
    "Full Table Scan",
    "Index Scan",
    "Index Only Scan",
    "Full Index Scan",
    "Unique Key Lookup",
    "Non-Unique Key Lookup",
    "Bitmap Heap Scan",
    "Bitmap Index Scan",
    "Nested Loop",
    "Join",
    "Hash Join",
    "Merge Join",
    "Materialize",
    "Limit",
    "Attached Subquery",
    "Hash",
    "Gather",
    "Gather Merge",
  ])
  .range([
    "#fbb4ae",
    "#fbb4ae",
    "#b3cde3",
    "#b3cde3",
    "#ccebc5",
    "#ccebc5",
    "#decbe4",
    "#decbe4",
    "#decbe4",
    "#decbe4",
    "#decbe4",
    "#decbe4",
    "#decbe4",
    "#fed9a6",
    "#fed9a6",
    "#fed9a6",
    "#fed9a6",
    "#ffffcc",
    "#f2f2f2",
    "#f2f2f2",
    "#f2f2f2",
    "#f2f2f2",
    "#f2f2f2",
  ]);
